"""Discourse REST API client used by the live-`init` pipeline (Sit 13).

The seeder talks to a Discourse instance over HTTP using the standard admin
API surface: `Api-Key` + `Api-Username` headers on every request. This file
deliberately mirrors `discourse_explorer/scraper.py`'s conventions — same
header names, same `requests.Session`-based plumbing, same retry behaviour
on 429 / 5xx — so a future maintainer recognising one client recognises the
other.

Scope: just the create-side of the API. Sit 14 will use these to push the
generators' output into the live forum (`pipeline.init`). Read paths stay
in the parent project's `scraper.py` — there's no need to duplicate them
here.

Discourse-specific quirks worth knowing:

* **Topic creation goes through `POST /posts.json`** — Discourse only has a
  posts endpoint; passing a `title` + `category` (no `topic_id`) is what
  causes a topic to be created (the response carries the new `topic_id`
  alongside the OP post `id`). This matches the
  `docs/discourse/DISCOURSE_JSON_TERMINOLOGY.md` model: a topic is just the
  metadata wrapper around its OP.
* **Backdating via `created_at`** is honoured only for requests
  authenticated as a master-key user — the admin key generated by
  Sit 13's `make api-key` (rails runner inside the bitnami container) has
  this. ISO 8601 strings (e.g. `"2025-04-26T10:30:00Z"`) are accepted.
* **Author impersonation** is per-request: the `Api-Username` header on a
  given call decides who the post / topic appears to be authored by.
  `_request(..., as_username=...)` swaps just that one header for the call
  without persisting on the session.
* **Tag pre-creation** is unnecessary in current Discourse versions — tags
  are auto-created when first associated with a topic, and the explicit
  tag-management endpoint is mostly relevant for renaming / grouping. The
  `create_tag` method here is a documented no-op so the seeder pipeline
  can call it idempotently for parity with categories / users.

Errors raise `DiscourseAPIError` with URL + status + body for diagnostics —
the alternative (raw `requests.HTTPError`) hides the response payload, which
is where Discourse's actual validation messages live.
"""

from __future__ import annotations

import time
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, Optional

import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry


# ---------------------------------------------------------------------------
# Retry config (mirrors discourse_explorer/scraper.py conventions)
# ---------------------------------------------------------------------------

# 3 retries with exponential backoff (factor 0.5 → waits 0.5s, 1s, 2s) on
# 429 + 5xx. Kept identical to the parent scraper's behaviour so a maintainer
# tuning one knows the other follows suit. POST is not in urllib3's default
# `allowed_methods`, so we list every verb we use explicitly.
_RETRY_TOTAL = 3
_RETRY_BACKOFF = 0.5
_RETRY_STATUS_FORCELIST = (429, 500, 502, 503, 504)
_RETRY_METHODS = frozenset({"GET", "POST", "PUT", "DELETE"})

# Sit 14.1: when urllib3's retry budget exhausts on 429, we recover at the
# `_request` layer with a fixed sleep + retry, up to N additional rounds. The
# 30-second window roughly matches Discourse's Rack::Attack burst-window
# default; bursts that fill the window in <30s recover cleanly. Keep
# `MAX_RETRIES` modest — repeated 429s past this point indicate a config
# issue (e.g. an untuned Discourse setting or a per-IP daily cap) rather
# than a transient burst.
_RATE_LIMIT_BACKOFF = 30.0
_RATE_LIMIT_MAX_RETRIES = 3


# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------


class DiscourseAPIError(RuntimeError):
    """Raised when a Discourse API call returns a non-2xx response.

    Carries the request URL, the HTTP status code, and the raw response body.
    Discourse's validation errors live in the body (`{"errors": [...]}`), so
    surfacing it verbatim is what makes diagnostics actually useful.
    """

    def __init__(self, *, url: str, status: int, body: str):
        self.url = url
        self.status = status
        self.body = body
        super().__init__(
            f"Discourse API call failed: {status} on {url}\n"
            f"  body: {body[:500]}{'...' if len(body) > 500 else ''}"
        )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _to_iso(ts: datetime) -> str:
    """Render a `datetime` as an ISO 8601 string Discourse accepts.

    Naive datetimes are assumed to be UTC; aware datetimes are converted to
    UTC and emitted with the trailing `Z` Discourse's API examples use. This
    is the single source of truth for `created_at` formatting — both
    `create_topic` and `create_post` call it so a future format change lands
    in one place.
    """
    if ts.tzinfo is None:
        ts = ts.replace(tzinfo=timezone.utc)
    else:
        ts = ts.astimezone(timezone.utc)
    # `isoformat()` emits `+00:00`; Discourse + every other tool accepts `Z`.
    return ts.replace(tzinfo=None).isoformat(timespec="seconds") + "Z"


# ---------------------------------------------------------------------------
# Client
# ---------------------------------------------------------------------------


@dataclass
class _CreatedPost:
    """Internal: the bits of a `POST /posts.json` response Sit 14 cares about.

    Returned as a plain dict from the public methods so callers don't pull in
    a private dataclass. Documented here so the field set is explicit.
    """

    id: int
    topic_id: int
    post_number: int


class DiscourseClient:
    """Thin Discourse REST API client for the seeder's live-`init` path.

    Methods return plain `dict` (or scalar) values so callers can json-dump
    them or pluck arbitrary fields without coupling to a dataclass schema.
    The `topic_id` / `id` (etc.) keys are documented per-method.

    Authentication is per-request via `Api-Key` + `Api-Username` headers — the
    same scheme `discourse_explorer/scraper.py` uses. The `api_username`
    constructor argument is the default; per-call `as_username` swaps it for
    one request (used to impersonate a regular user when authoring a topic
    or reply).
    """

    def __init__(
        self,
        base_url: str,
        api_key: str,
        api_username: str,
        *,
        timeout: tuple[float, float] = (5.0, 30.0),
    ):
        if not base_url:
            raise ValueError("DiscourseClient: base_url is required")
        if not api_key:
            raise ValueError("DiscourseClient: api_key is required")
        if not api_username:
            raise ValueError("DiscourseClient: api_username is required")

        self.base_url = base_url.rstrip("/")
        self.api_key = api_key
        self.api_username = api_username
        # Timeout is the `requests` (connect, read) tuple — strictly per-attempt
        # enforced. The earlier float form (`timeout=30.0`) was observed during
        # the Sit 14 verification to NOT release a half-closed-keepalive hang
        # (sockets pinned in CLOSE_WAIT after Discourse FIN'd a long-running
        # POST), even after the configured 30s elapsed. The tuple form passes
        # the read deadline through to urllib3 cleanly so the Retry adapter
        # sees a real timeout exception to act on.
        self.timeout = timeout
        self.session = self._build_session()

    # -- session + transport ------------------------------------------------

    @staticmethod
    def _build_session() -> requests.Session:
        """Build a `requests.Session` pre-wired with retries on 429 + 5xx.

        Mirrors `discourse_explorer/scraper.py` — three retries, exponential
        backoff factor 0.5, status-forcelist over the standard rate-limit +
        upstream-error codes. POST is included in the allowed methods because
        the create endpoints all use POST.
        """
        retry = Retry(
            total=_RETRY_TOTAL,
            backoff_factor=_RETRY_BACKOFF,
            status_forcelist=_RETRY_STATUS_FORCELIST,
            allowed_methods=_RETRY_METHODS,
            raise_on_status=False,
            # urllib3 defaults to honouring `Retry-After` from the server. The
            # Sit 14 verification surfaced Discourse's `Rack::Attack` middleware
            # returning 429 with `Retry-After` set to thousands of seconds
            # (the "you've hit the per-IP burst limit, come back in an hour"
            # hint), and urllib3 was `time.sleep()`-ing inside the retry loop
            # for the full duration — a pure sleep deadlock with no network
            # activity, no CPU, and no way for the per-attempt timeout to fire.
            # Disabling this makes urllib3 fall back to its own exponential
            # backoff (`backoff_factor`); persistent 429s exhaust retries
            # quickly and surface as a real exception we can act on.
            respect_retry_after_header=False,
            # Cap individual backoff sleeps so a server-side 5xx storm can't
            # produce multi-minute delays even with backoff_factor=0.5.
            backoff_max=15,
        )
        adapter = HTTPAdapter(max_retries=retry)
        session = requests.Session()
        session.mount("http://", adapter)
        session.mount("https://", adapter)
        # Disable HTTP keep-alive for the duration of this client. A bulk push
        # against a localhost Discourse stack is exactly the workload where
        # keep-alive helps least: the Sidekiq job-processing latency between
        # requests already dwarfs the TCP-handshake savings (~0-3 ms per
        # request), and the Sit-14 verification observed Discourse FIN'ing
        # long-running POSTs mid-response — leaving the next reused socket in
        # CLOSE_WAIT and wedging the python `requests` read indefinitely.
        # Forcing `Connection: close` makes every request open a fresh TCP
        # connection so a half-closed prior socket can't poison the pool.
        session.headers["Connection"] = "close"
        return session

    def _headers(self, *, as_username: Optional[str] = None) -> dict[str, str]:
        """Return the auth + UA headers Discourse expects.

        `as_username` is a per-call override. None means use the client's
        default `api_username`; passing an explicit username impersonates that
        user for the call (Discourse honours the `Api-Username` header value
        on every request, so swapping it is sufficient — no separate
        `act_as` parameter needed).
        """
        return {
            "Api-Key": self.api_key,
            "Api-Username": as_username or self.api_username,
            "User-Agent": "DiscourseExplorerSampleSeeder/1.0",
            "Accept": "application/json",
        }

    def _request(
        self,
        method: str,
        path: str,
        *,
        json: Optional[dict[str, Any]] = None,
        params: Optional[dict[str, Any]] = None,
        as_username: Optional[str] = None,
    ) -> Any:
        """Issue a single request and parse JSON, raising `DiscourseAPIError`.

        Centralises URL construction, header injection, timeout, and error
        handling so the public methods stay short. `as_username` swaps the
        `Api-Username` header for this call only — used by `create_topic` /
        `create_post` to impersonate the OP author.

        On 429 (Discourse's `Rack::Attack` per-IP burst limit firing), this
        method does its own bounded sleep-and-retry: urllib3's retry layer is
        configured to NOT honour `Retry-After` (Discourse sets it to thousands
        of seconds, which would deadlock the push), so a sustained 429 burst
        bubbles back here, and we recover by sleeping for `_RATE_LIMIT_BACKOFF`
        seconds at a time, up to `_RATE_LIMIT_MAX_RETRIES` rounds. Master API
        keys bypass per-user rate limits but NOT the per-IP `Rack::Attack`
        middleware, so this matters even for the seeder's privileged caller.
        """
        url = f"{self.base_url}{path}"
        for attempt in range(_RATE_LIMIT_MAX_RETRIES + 1):
            try:
                response = self.session.request(
                    method,
                    url,
                    headers=self._headers(as_username=as_username),
                    json=json,
                    params=params,
                    timeout=self.timeout,
                )
            except requests.exceptions.RequestException as exc:
                # Network-level failure (DNS, connection refused, timeout).
                # Wrap in our error type so callers don't have to catch two
                # families.
                raise DiscourseAPIError(
                    url=url, status=0, body=f"transport error: {exc}"
                ) from exc

            if response.status_code == 429 and attempt < _RATE_LIMIT_MAX_RETRIES:
                # Per-IP burst hit Discourse's Rack::Attack window. Sleep a
                # fixed window, then re-issue from scratch (don't reuse the
                # exhausted urllib3 Retry budget). The fixed sleep is short
                # enough that a transient burst recovers without operator
                # intervention but long enough that we don't immediately
                # re-trigger the same window.
                time.sleep(_RATE_LIMIT_BACKOFF)
                continue

            if not 200 <= response.status_code < 300:
                raise DiscourseAPIError(
                    url=url, status=response.status_code, body=response.text
                )

            # Most endpoints return JSON; a few (DELETE) may return empty
            # bodies.
            if not response.content:
                return None
            try:
                return response.json()
            except ValueError:
                # 2xx with non-JSON content is unusual but not fatal — return
                # raw.
                return response.text

        # Exhausted 429 retries — surface as a regular DiscourseAPIError so the
        # push's existing soft-skip path (in pipeline.push_forum) can record
        # the failure without aborting the whole run.
        raise DiscourseAPIError(
            url=url,
            status=429,
            body=(
                f"rate-limited: {_RATE_LIMIT_MAX_RETRIES + 1} attempts with "
                f"{_RATE_LIMIT_BACKOFF}s backoff between each"
            ),
        )

    # -- public API ---------------------------------------------------------

    def grant_moderator(self, user_id: int) -> None:
        """Promote `user_id` to moderator via the admin API.

        Sit 14.1: Discourse's per-user rate limits (`max_topics_in_first_day`,
        `max_topics_per_day`, `rate_limit_create_post`, etc.) are checked via
        `RateLimiter.rate_unlimited?`, which short-circuits to true when
        `user.staff?` is true (staff = admin OR moderator). The seeder
        promotes every seeded user to moderator immediately after creation
        so the push isn't subject to *any* per-user rate cap — present or
        future, named or unnamed. Without this bypass the seeder has to
        enumerate (and keep up with) Discourse's full rate-limit surface,
        which in practice is a moving target.

        Cosmetic side effect: each seeded user appears with a "moderator"
        badge in the Discourse UI. For a synthetic regression-test forum
        this is acceptable; for a production bulk-import tool it would not
        be.

        Verified against `app/controllers/admin/users_controller.rb`
        (`grant_moderation` action) + `lib/rate_limiter.rb`
        (`rate_unlimited?` check) in the bitnamilegacy/discourse 3.4.6
        image. Endpoint: `PUT /admin/users/:id/grant_moderation.json`,
        no body required.
        """
        if not isinstance(user_id, int) or user_id <= 0:
            raise ValueError(
                f"grant_moderator: user_id must be a positive int, got {user_id!r}"
            )
        self._request("PUT", f"/admin/users/{user_id}/grant_moderation.json")

    def set_site_setting(self, name: str, value: Any) -> None:
        """Update a Discourse site setting via the admin API.

        PUTs to `/admin/site_settings/<name>.json` with the value. Used by
        the seeder to lift the per-user post rate-limit on the localhost
        test stack so a multi-hundred-POST push doesn't spend most of its
        wall-clock time waiting on `Retry-After` cool-downs. The setting
        being tuned (`rate_limit_create_post`) controls *how fast* a user
        can POST — it does NOT change what the parent project's scraper
        sees on read paths. Tuning it here is the same kind of admin
        operation a real forum operator would perform when running a
        bulk import. Requires admin auth (the rake-minted master API key
        has it).

        Returns nothing on success; surfaces 422 / etc. as
        `DiscourseAPIError` like the other helpers.
        """
        if not name:
            raise ValueError("set_site_setting: name must be non-empty")
        # Discourse's settings endpoint expects the value under the same
        # key as the setting name. Booleans are stringified ("true" /
        # "false"); numbers and strings pass through.
        raw_value = str(value).lower() if isinstance(value, bool) else value
        self._request(
            "PUT", f"/admin/site_settings/{name}.json", json={name: raw_value}
        )

    def create_category(
        self,
        name: str,
        *,
        color: str = "BF1E2E",
        text_color: str = "FFFFFF",
        description: Optional[str] = None,
    ) -> int:
        """Create a category and return its numeric id.

        Posts to `/categories.json`. `color` + `text_color` are 6-char hex
        without the leading `#`, as Discourse stores them. Returns the
        new category's `id`.
        """
        payload: dict[str, Any] = {
            "name": name,
            "color": color,
            "text_color": text_color,
        }
        if description is not None:
            payload["description"] = description

        result = self._request("POST", "/categories.json", json=payload)
        # Response shape: `{"category": {"id": N, ...}}`.
        category = result.get("category", {})
        cat_id = category.get("id")
        if not isinstance(cat_id, int):
            raise DiscourseAPIError(
                url=f"{self.base_url}/categories.json",
                status=200,
                body=f"missing category.id in response: {result}",
            )
        return cat_id

    def create_tag(self, name: str) -> str:
        """No-op tag creator — current Discourse auto-creates tags on use.

        Returns `name` so callers can treat the result as the canonical tag
        identifier. We expose this method for two reasons:
        1. **Pipeline parity.** Sit 14's pipeline calls `create_<entity>` for
           every generated artefact; having `create_tag` keeps the loop
           uniform without a special-case branch.
        2. **Future-proofing.** If a future Discourse version requires
           explicit tag pre-creation again (or you need to set tag-group
           membership), the implementation lands here without any caller
           changes.

        Discourse versions verified against (April 2026, bitnami/discourse
        2026.x): tags created lazily when first attached to a topic via
        `create_topic`'s `tags` field. No POST needed.
        """
        if not name:
            raise ValueError("create_tag: name must be non-empty")
        return name

    def create_user(
        self,
        username: str,
        password: str,
        email: str,
        *,
        name: Optional[str] = None,
        active: bool = True,
        approved: bool = True,
    ) -> int:
        """Create a user and return the new user's id.

        Two-step flow because Discourse's `/users.json` POST endpoint does
        NOT consistently return a `user_id` in its response body. The shape
        depends on the activation / approval branch the request lands on:

        * Self-signup (no `active=true`) → `{"success": true, "active": false,
          "message": "...check your email..."}`. No `user_id`.
        * Admin-created with auto-activation (the `active=true` we pass) →
          `{"success": true, "active": true, "message": "Your account is
          activated and ready to use."}`. Often no `user_id` either, despite
          older docs and some client examples implying otherwise.
        * Older Discourse versions / certain config combos → `{"success":
          true, "user_id": N, ...}`. Happy-path early return covers this.

        Robust path: after the POST returns `success: true`, fetch the
        canonical user resource via `GET /u/<username>.json` and read
        `user.id` from there. Mirrors what Discourse's own admin UI + the
        official `discourse_api` Ruby gem do; documented at
        meta.discourse.org/t/discourse-api-documentation/22706 (the user
        resource is the source of truth, the create response is a status
        envelope).

        Posts to `/users.json` with `active=True` + `approved=True` so the
        user can immediately author posts (no email-verification round-trip).
        `name` defaults to `username` if not provided — Discourse requires a
        non-empty `name` even when the site allows anonymous-style usernames.
        """
        payload: dict[str, Any] = {
            "username": username,
            "email": email,
            "password": password,
            "name": name if name is not None else username,
            "active": active,
            "approved": approved,
        }

        result = self._request("POST", "/users.json", json=payload)

        # `success` is the only field guaranteed to be present on this
        # endpoint — surface its absence (or a False value) as a real error
        # so callers don't silently look up a user that wasn't created.
        if not isinstance(result, dict) or not result.get("success"):
            message = (
                result.get("message")
                if isinstance(result, dict)
                else None
            )
            raise DiscourseAPIError(
                url=f"{self.base_url}/users.json",
                status=200,
                body=f"user creation failed: {message or result}",
            )

        # Happy path: older Discourse versions echo `user_id` directly.
        user_id = result.get("user_id")
        if isinstance(user_id, int):
            return user_id

        # Robust path: look up the user resource by username. Reuses the
        # same `_request` so retry / error handling is identical to the POST.
        lookup = self._request("GET", f"/u/{username}.json")
        if isinstance(lookup, dict):
            user = lookup.get("user")
            if isinstance(user, dict):
                fetched_id = user.get("id")
                if isinstance(fetched_id, int):
                    return fetched_id

        raise DiscourseAPIError(
            url=f"{self.base_url}/u/{username}.json",
            status=200,
            body=f"missing user.id in /u/{username}.json response: {lookup}",
        )

    def create_topic(
        self,
        title: str,
        raw: str,
        *,
        category_id: int,
        tags: Optional[list[str]] = None,
        created_at: Optional[datetime] = None,
        author_username: Optional[str] = None,
    ) -> dict[str, Any]:
        """Create a new topic by posting its OP via `POST /posts.json`.

        Discourse has no separate topic-creation endpoint; the posts endpoint
        creates a topic when no `topic_id` is supplied (signalled by the
        presence of `title` + `category`). Returns the parsed response dict —
        callers want `topic_id` (the new topic's id) and `id` (the OP post's
        id).

        `tags` is a list of tag names; tags are auto-created if they don't
        exist yet (see `create_tag` docstring). `created_at` backdates the
        topic — only honoured by master-key users (the bitnami admin set up
        by `make api-key` has this). `author_username` impersonates the OP
        author for this call via the per-request `Api-Username` header.
        """
        payload: dict[str, Any] = {
            "title": title,
            "raw": raw,
            "category": category_id,
        }
        if tags:
            payload["tags"] = list(tags)
        if created_at is not None:
            payload["created_at"] = _to_iso(created_at)

        result = self._request(
            "POST", "/posts.json", json=payload, as_username=author_username
        )
        # Validate the keys callers will look at so a malformed response is
        # caught at the boundary rather than in pipeline glue.
        if not isinstance(result, dict) or "topic_id" not in result or "id" not in result:
            raise DiscourseAPIError(
                url=f"{self.base_url}/posts.json",
                status=200,
                body=f"missing topic_id/id in response: {result}",
            )
        return result

    def create_post(
        self,
        topic_id: int,
        raw: str,
        *,
        reply_to_post_number: Optional[int] = None,
        created_at: Optional[datetime] = None,
        author_username: Optional[str] = None,
    ) -> dict[str, Any]:
        """Create a reply on an existing topic via `POST /posts.json`.

        With `topic_id` set (and no `title`), Discourse appends a post to
        that topic. `reply_to_post_number` records the parent within the
        topic — the `post_number` of the post being replied to (NOT the
        post `id`); see `docs/discourse/DISCOURSE_JSON_TERMINOLOGY.md` for
        the distinction. `created_at` and `author_username` behave as in
        `create_topic`.
        """
        payload: dict[str, Any] = {
            "topic_id": topic_id,
            "raw": raw,
        }
        if reply_to_post_number is not None:
            payload["reply_to_post_number"] = reply_to_post_number
        if created_at is not None:
            payload["created_at"] = _to_iso(created_at)

        result = self._request(
            "POST", "/posts.json", json=payload, as_username=author_username
        )
        if not isinstance(result, dict) or "id" not in result:
            raise DiscourseAPIError(
                url=f"{self.base_url}/posts.json",
                status=200,
                body=f"missing id in response: {result}",
            )
        return result

    # -- read-side helpers (Sit 15.1, used by `pipeline.push_extension`) -----

    def list_categories(self) -> list[dict[str, Any]]:
        """Return all categories visible to the API caller.

        Reads `/categories.json` and unwraps the
        `category_list.categories[]` envelope. Each entry has at least
        `id`, `name`, `slug` (plus colour/parent fields the seeder
        ignores). `push_extension` uses this to map category names back
        to ids without re-running `create_category`.
        """
        result = self._request("GET", "/categories.json")
        if not isinstance(result, dict):
            raise DiscourseAPIError(
                url=f"{self.base_url}/categories.json",
                status=200,
                body=f"unexpected categories shape: {result}",
            )
        cat_list = result.get("category_list", {})
        cats = cat_list.get("categories", [])
        if not isinstance(cats, list):
            raise DiscourseAPIError(
                url=f"{self.base_url}/categories.json",
                status=200,
                body=f"category_list.categories not a list: {cats}",
            )
        return cats

    def list_topics_in_category(
        self, category_id: int, slug: str
    ) -> list[dict[str, Any]]:
        """Return every topic in a category, paging until exhausted.

        Reads `/c/<slug>/<id>.json?page=N`. Discourse's per-page list is
        capped at 30 topics (default `topics_per_page`); we walk pages
        until a response carries an empty list. Each returned dict is the
        Discourse `topic_list.topics[]` shape — at minimum `id`, `title`,
        `slug`, `category_id`, `posts_count`. Used by `push_extension` to
        build a `seeded_title -> discourse_topic_id` map so appended
        replies land on the right base topic.
        """
        topics: list[dict[str, Any]] = []
        page = 0
        while True:
            result = self._request(
                "GET", f"/c/{slug}/{category_id}.json", params={"page": page}
            )
            if not isinstance(result, dict):
                raise DiscourseAPIError(
                    url=f"{self.base_url}/c/{slug}/{category_id}.json",
                    status=200,
                    body=f"unexpected category-page shape: {result}",
                )
            page_topics = (
                result.get("topic_list", {}).get("topics", [])
            )
            if not page_topics:
                break
            topics.extend(page_topics)
            page += 1
            # Defensive cap — a category with thousands of topics doesn't
            # belong in a sample-seeder test forum, but we still want to
            # stop walking if Discourse returns the same page forever.
            if page > 200:
                break
        return topics
